### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by climu** [mrogaski/django-discord-bind#1]
Hi, 
I am considering using this app for [a project](http://openstudyroom.org) of mine, but I am not sure to understand exaclty what it does.

I will do some testing, but I was thinking some more docs could help.
Just pointing that out.

**Comment by mrogaski** [comment]
It's just a way for you to control access to a Discord server.  It uses OAuth2 to do identify what the Django user's Discord ID is and also to let them join the server without seeing the invite link.  It's a way to have a members-only server.

**Comment by climu** [comment]
Thanks for your work.

**Comment by chandler37** [comment]
Thanks for this! I will fork it to support 'sign in with discord' for my app and to power a discord bot for that app. I see that you're verifying the 'state' parameter. I should be able to do away with the guild.join scope, remove @login_required, and create Users if they don't already exist. I think my app will want to think of a (discord user, guild) pair as a django User.

**Comment by mrogaski** [comment]
@chandler37 If you want to use Discord as an authentication back-end for Django, you might want to look at [django-allauth](https://django-allauth.readthedocs.io/en/latest/index.html).
